### ISSUE TITLE
Engrampa not opening / listing 7z password compressed files when the option of password protect file names was chosen for create the file

### ISSUE THREAD

**Issue by acastan** [mate-desktop/engrampa#510]
#### Expected behaviour

In a 7z password compressed files when the option of password protect file names was chosen for create the file, it is expected that when you open the file, Engrampa ask for the password, and if the password is fine the listing the content (files) inside the compressed .7z files

#### Actual behaviour

In Debian Testing, with Engrampa 1.26.1-3, since moved from p7zip to 7zip, nothing is happening. Engrampa don't ask for the password and don't show the content.

#### Steps to reproduce the behaviour

(1) In Debian Testing, with Engrampa choose some documents or a folder to compress. Choose extension .7z

(2) Choose password protection and choose a password

(3) and -IMPORTANT- choose the option of password protect also the filenames too 

Then try to open the file again with Engrampa and it didn't show any content and don't ask for password. But I still can work with the file from command line with command 7zip

#### MATE general version

Mate Desktop in Debian Testing is 1.26.2-1 , today 1 february 2024

#### Package version

Engrampa in Debian Testing is 1.26.1-3 , today 1 february 2024

#### Linux Distribution

Debian Testing 

#### Link to bugreport of your Distribution (requirement)

Excuse my poor English. I think I detect this issue happening when in Debian Testing moved from p7zip to 7zip weeks ago, and the package Engrampa was 1.26.1-2.

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061510

Then somebody report this bug that was solved and theoretically fixed in Engrampa 1.26.1-3 , but this patch don't fix the issue I am describing, so I tried to report the bug, but Debian Bug Reporting System was a little bit tricky to me, and finally I wrote to the Engrama Debian package maintainers that I found in:

   https://tracker.debian.org/pkg/engrampa

They are very nice and soon answer me that they don't have a fix for this and I should report the problem to the Engrampa Maintainers/Upstream Developers here.

**Comment by zhuyaliang** [comment]
What is the version of ```7zip```

**Comment by acastan** [comment]
The 7z comand version is 23.01 and the 7zip package version is 23.01+dfsg-8

**Comment by acastan** [comment]
I tested now Engrampa 1.26.2 and the issue is still happening as with Engrampa 1.26.1

**Comment by zhuyaliang** [comment]
I just finished my vacation, and I will solve this problem soon

**Comment by acastan** [comment]
This days I was trying to understand Engrampa code to see if I can help to fix the issue, but after your last comment I installed and tried Gnome File-Roller in my Debian Testing, and it have the same issue. So, maybe it's an issue with the way Debian Maintainers packed 7zip, and not an issue with Engrampa or File-Roller.

**Comment by qykth-git** [comment]
Hello Engrampa maintainer and @acastan , 
I am a maintainer of Debian 7-Zip package.

On my quick glance, I think the error comes from insufficient functionality of file list parser.
Check the line from here.
https://github.com/mate-desktop/engrampa/blob/1f1fb3c13f8fe9a6e33562a145d66f1900ed7b52/src/fr-command-7z.c#L101

Engrampa's 7z list parser wants parsing start point from 7zip's file list output text.

If non-encrypted 7z archive or content-only encrypted archive, the start point is `"----------"`.
https://github.com/mate-desktop/engrampa/blob/1f1fb3c13f8fe9a6e33562a145d66f1900ed7b52/src/fr-command-7z.c#L122

But header-encrypted 7z archive (use `-mhe` option for `7z`), there are no way to determine parsing start point.
And it provides empty file list on Engrampa GUI.

I think you might needs new file list parser for upstream 7-Zip support.

**Comment by zhuyaliang** [comment]
@qykth-git Are you interested in fixing this issue? I am always ready to review the code

**Comment by zhuyaliang** [comment]
@qykth-git @acastan I just checked the code and found that the old ```p7zip``` does not require a password to view the encrypted compressed file list, while the new ```7-Zip``` requires a password, resulting in a failure to view the list

**Comment by zhuyaliang** [comment]
This #513  has fixed the issue, please test the code

**Comment by qykth-git** [comment]
@zhuyaliang 
Thanks. It worked with header-encrypted archives on my machine.

**Comment by zhuyaliang** [comment]
@acastan Please confirm if the issue has been fixed

**Comment by acastan** [comment]
I cloned with git, compiled and installed in Debian Testing , but still not working for me.

**Comment by acastan** [comment]
Sorry for my delay.

I cloned Engrampa, compiled the source code with the pull request #513 and installed in Debian Testing, and the issue has been fixed.

Thank you

**Comment by ewangi** [comment]
This issue still exists on Linux Mint 22 (Engrampa 1.26.2; 7zip 23.01+dfsg-11).

**Comment by lukefromdc** [comment]
Looks like we need a cherrypick to 1.26 to fix this in distros not shipping 1.28 and then a new 1.26 release. Unfortunately, a MATE-wide Travis CI issue is blocking deployment of any new releases. It's another "gem" issue and I don't know any Ruby or enough about Travis to fix it.
